#include <stdio.h>
#include "hocdec.h"
extern int nrnmpi_myid;
extern int nrn_nobanner_;

extern "C" void _ALU_reg(void);
extern "C" void _CaDynamics_DC0_reg(void);
extern "C" void _Ca_HVA2_reg(void);
extern "C" void _Ca_LVAst_reg(void);
extern "C" void _ConductanceSource_reg(void);
extern "C" void _CoreNEURONArtificialCell_reg(void);
extern "C" void _DetAMPANMDA_reg(void);
extern "C" void _DetGABAAB_reg(void);
extern "C" void _GluSynapse_reg(void);
extern "C" void _Ih_reg(void);
extern "C" void _K_Pst_reg(void);
extern "C" void _K_Tst_reg(void);
extern "C" void _KdShu2007_reg(void);
extern "C" void _Kv7_reg(void);
extern "C" void _MembraneCurrentSource_reg(void);
extern "C" void _NaTg_reg(void);
extern "C" void _NaTg_axon_reg(void);
extern "C" void _NaTg_persistent_axon_reg(void);
extern "C" void _NaTg_persistent_somadend_reg(void);
extern "C" void _NaTg_somadend_reg(void);
extern "C" void _Nap_Et2_reg(void);
extern "C" void _ProbAMPANMDA_EMS_reg(void);
extern "C" void _ProbGABAAB_EMS_reg(void);
extern "C" void _SK_E2_reg(void);
extern "C" void _SKv3_1_reg(void);
extern "C" void _SonataReportHelper_reg(void);
extern "C" void _SonataReports_reg(void);
extern "C" void _StochKv3_reg(void);
extern "C" void _TTXDynamicsSwitch_reg(void);
extern "C" void _gap_reg(void);
extern "C" void _netstim_inhpoisson_reg(void);
extern "C" void _vecevent_reg(void);

extern "C" void modl_reg() {
  if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
    fprintf(stderr, "Additional mechanisms from files\n");
    fprintf(stderr, " \"mods_dir//ALU.mod\"");
    fprintf(stderr, " \"mods_dir//CaDynamics_DC0.mod\"");
    fprintf(stderr, " \"mods_dir//Ca_HVA2.mod\"");
    fprintf(stderr, " \"mods_dir//Ca_LVAst.mod\"");
    fprintf(stderr, " \"mods_dir//ConductanceSource.mod\"");
    fprintf(stderr, " \"mods_dir//CoreNEURONArtificialCell.mod\"");
    fprintf(stderr, " \"mods_dir//DetAMPANMDA.mod\"");
    fprintf(stderr, " \"mods_dir//DetGABAAB.mod\"");
    fprintf(stderr, " \"mods_dir//GluSynapse.mod\"");
    fprintf(stderr, " \"mods_dir//Ih.mod\"");
    fprintf(stderr, " \"mods_dir//K_Pst.mod\"");
    fprintf(stderr, " \"mods_dir//K_Tst.mod\"");
    fprintf(stderr, " \"mods_dir//KdShu2007.mod\"");
    fprintf(stderr, " \"mods_dir//Kv7.mod\"");
    fprintf(stderr, " \"mods_dir//MembraneCurrentSource.mod\"");
    fprintf(stderr, " \"mods_dir//NaTg.mod\"");
    fprintf(stderr, " \"mods_dir//NaTg_axon.mod\"");
    fprintf(stderr, " \"mods_dir//NaTg_persistent_axon.mod\"");
    fprintf(stderr, " \"mods_dir//NaTg_persistent_somadend.mod\"");
    fprintf(stderr, " \"mods_dir//NaTg_somadend.mod\"");
    fprintf(stderr, " \"mods_dir//Nap_Et2.mod\"");
    fprintf(stderr, " \"mods_dir//ProbAMPANMDA_EMS.mod\"");
    fprintf(stderr, " \"mods_dir//ProbGABAAB_EMS.mod\"");
    fprintf(stderr, " \"mods_dir//SK_E2.mod\"");
    fprintf(stderr, " \"mods_dir//SKv3_1.mod\"");
    fprintf(stderr, " \"mods_dir//SonataReportHelper.mod\"");
    fprintf(stderr, " \"mods_dir//SonataReports.mod\"");
    fprintf(stderr, " \"mods_dir//StochKv3.mod\"");
    fprintf(stderr, " \"mods_dir//TTXDynamicsSwitch.mod\"");
    fprintf(stderr, " \"mods_dir//gap.mod\"");
    fprintf(stderr, " \"mods_dir//netstim_inhpoisson.mod\"");
    fprintf(stderr, " \"mods_dir//vecevent.mod\"");
    fprintf(stderr, "\n");
  }
  _ALU_reg();
  _CaDynamics_DC0_reg();
  _Ca_HVA2_reg();
  _Ca_LVAst_reg();
  _ConductanceSource_reg();
  _CoreNEURONArtificialCell_reg();
  _DetAMPANMDA_reg();
  _DetGABAAB_reg();
  _GluSynapse_reg();
  _Ih_reg();
  _K_Pst_reg();
  _K_Tst_reg();
  _KdShu2007_reg();
  _Kv7_reg();
  _MembraneCurrentSource_reg();
  _NaTg_reg();
  _NaTg_axon_reg();
  _NaTg_persistent_axon_reg();
  _NaTg_persistent_somadend_reg();
  _NaTg_somadend_reg();
  _Nap_Et2_reg();
  _ProbAMPANMDA_EMS_reg();
  _ProbGABAAB_EMS_reg();
  _SK_E2_reg();
  _SKv3_1_reg();
  _SonataReportHelper_reg();
  _SonataReports_reg();
  _StochKv3_reg();
  _TTXDynamicsSwitch_reg();
  _gap_reg();
  _netstim_inhpoisson_reg();
  _vecevent_reg();
}
